export const GET_ALL = 'GET_ALL';
export const GET_DETAIL = 'GET_DETAIL';
export const GET_NAME = ' GET_NAME';
export const GET_TEMPERAMENT = 'GET_TEMPERAMENT';
export const SET_PAGE = 'SET_PAGE';
export const ORDER_NAME = 'ORDER_NAME';
export const ORDER_TEMPERAMENT = 'ORDER_TEMPERAMENT'
export const ORDER_WEIGHT = 'ORDER_WEIGHT'
export const CREATED_IN_DB = 'CREATED_IN_DB'
export const SET_ORDER = 'SET_ORDER'
export const SET_FILTER = 'SET_FILTER'
export const SET_ORDERMAX = 'SET_ORDERMAX'